// Code generated by goctl. DO NOT EDIT!
// Source: pay.proto

package payrpc

import (
	"context"

	"MaoerMovie/service/pay-rpc/types/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePayRequest     = pb.CreatePayRequest
	CreatePayResponse    = pb.CreatePayResponse
	GetPayDetailRequest  = pb.GetPayDetailRequest
	GetPayDetailResponse = pb.GetPayDetailResponse
	SetPayStatusRequest  = pb.SetPayStatusRequest
	SetPayStatusResponse = pb.SetPayStatusResponse

	PayRpc interface {
		CreatePay(ctx context.Context, in *CreatePayRequest, opts ...grpc.CallOption) (*CreatePayResponse, error)
		SetPayPaid(ctx context.Context, in *SetPayStatusRequest, opts ...grpc.CallOption) (*SetPayStatusResponse, error)
		SetPayPaidRollback(ctx context.Context, in *SetPayStatusRequest, opts ...grpc.CallOption) (*SetPayStatusResponse, error)
		GetPayDetail(ctx context.Context, in *GetPayDetailRequest, opts ...grpc.CallOption) (*GetPayDetailResponse, error)
	}

	defaultPayRpc struct {
		cli zrpc.Client
	}
)

func NewPayRpc(cli zrpc.Client) PayRpc {
	return &defaultPayRpc{
		cli: cli,
	}
}

func (m *defaultPayRpc) CreatePay(ctx context.Context, in *CreatePayRequest, opts ...grpc.CallOption) (*CreatePayResponse, error) {
	client := pb.NewPayRpcClient(m.cli.Conn())
	return client.CreatePay(ctx, in, opts...)
}

func (m *defaultPayRpc) SetPayPaid(ctx context.Context, in *SetPayStatusRequest, opts ...grpc.CallOption) (*SetPayStatusResponse, error) {
	client := pb.NewPayRpcClient(m.cli.Conn())
	return client.SetPayPaid(ctx, in, opts...)
}

func (m *defaultPayRpc) SetPayPaidRollback(ctx context.Context, in *SetPayStatusRequest, opts ...grpc.CallOption) (*SetPayStatusResponse, error) {
	client := pb.NewPayRpcClient(m.cli.Conn())
	return client.SetPayPaidRollback(ctx, in, opts...)
}

func (m *defaultPayRpc) GetPayDetail(ctx context.Context, in *GetPayDetailRequest, opts ...grpc.CallOption) (*GetPayDetailResponse, error) {
	client := pb.NewPayRpcClient(m.cli.Conn())
	return client.GetPayDetail(ctx, in, opts...)
}
