// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package orderrpc

import (
	"context"

	"MaoerMovie/service/order-rpc/types/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderRequest       = pb.CreateOrderRequest
	CreateOrderResponse      = pb.CreateOrderResponse
	GetOrderDetailRequest    = pb.GetOrderDetailRequest
	GetOrderDetailResponse   = pb.GetOrderDetailResponse
	GetOrderListRequest      = pb.GetOrderListRequest
	GetOrderListResponse     = pb.GetOrderListResponse
	GetPaidOrderListResponse = pb.GetPaidOrderListResponse
	GetSoldSeatsRequest      = pb.GetSoldSeatsRequest
	GetSoldSeatsResponse     = pb.GetSoldSeatsResponse
	OrderDetail              = pb.OrderDetail
	SetOrderPaidRequest      = pb.SetOrderPaidRequest
	SetOrderPaidResponse     = pb.SetOrderPaidResponse

	OrderRpc interface {
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		GetOrderDetail(ctx context.Context, in *GetOrderDetailRequest, opts ...grpc.CallOption) (*GetOrderDetailResponse, error)
		GetOrderList(ctx context.Context, in *GetOrderListRequest, opts ...grpc.CallOption) (*GetOrderListResponse, error)
		GetPaidOrderList(ctx context.Context, in *GetOrderListRequest, opts ...grpc.CallOption) (*GetPaidOrderListResponse, error)
		GetSoldSeats(ctx context.Context, in *GetSoldSeatsRequest, opts ...grpc.CallOption) (*GetSoldSeatsResponse, error)
		SetOrderPaid(ctx context.Context, in *SetOrderPaidRequest, opts ...grpc.CallOption) (*SetOrderPaidResponse, error)
		SetOrderPaidRollback(ctx context.Context, in *SetOrderPaidRequest, opts ...grpc.CallOption) (*SetOrderPaidResponse, error)
		CreateOrderRollback(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderRequest, error)
	}

	defaultOrderRpc struct {
		cli zrpc.Client
	}
)

func NewOrderRpc(cli zrpc.Client) OrderRpc {
	return &defaultOrderRpc{
		cli: cli,
	}
}

func (m *defaultOrderRpc) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) GetOrderDetail(ctx context.Context, in *GetOrderDetailRequest, opts ...grpc.CallOption) (*GetOrderDetailResponse, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.GetOrderDetail(ctx, in, opts...)
}

func (m *defaultOrderRpc) GetOrderList(ctx context.Context, in *GetOrderListRequest, opts ...grpc.CallOption) (*GetOrderListResponse, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.GetOrderList(ctx, in, opts...)
}

func (m *defaultOrderRpc) GetPaidOrderList(ctx context.Context, in *GetOrderListRequest, opts ...grpc.CallOption) (*GetPaidOrderListResponse, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.GetPaidOrderList(ctx, in, opts...)
}

func (m *defaultOrderRpc) GetSoldSeats(ctx context.Context, in *GetSoldSeatsRequest, opts ...grpc.CallOption) (*GetSoldSeatsResponse, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.GetSoldSeats(ctx, in, opts...)
}

func (m *defaultOrderRpc) SetOrderPaid(ctx context.Context, in *SetOrderPaidRequest, opts ...grpc.CallOption) (*SetOrderPaidResponse, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.SetOrderPaid(ctx, in, opts...)
}

func (m *defaultOrderRpc) SetOrderPaidRollback(ctx context.Context, in *SetOrderPaidRequest, opts ...grpc.CallOption) (*SetOrderPaidResponse, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.SetOrderPaidRollback(ctx, in, opts...)
}

func (m *defaultOrderRpc) CreateOrderRollback(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderRequest, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CreateOrderRollback(ctx, in, opts...)
}
