// Code generated by goctl. DO NOT EDIT!
// Source: cinema.proto

package server

import (
	"context"

	"MaoerMovie/service/cinema-rpc/internal/logic"
	"MaoerMovie/service/cinema-rpc/internal/svc"
	"MaoerMovie/service/cinema-rpc/types/pb"
)

type CinemaRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCinemaRpcServer
}

func NewCinemaRpcServer(svcCtx *svc.ServiceContext) *CinemaRpcServer {
	return &CinemaRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *CinemaRpcServer) GetCinemaList(ctx context.Context, in *pb.CinemaListRequest) (*pb.CinemaListResponse, error) {
	l := logic.NewGetCinemaListLogic(ctx, s.svcCtx)
	return l.GetCinemaList(in)
}

func (s *CinemaRpcServer) GetConditionList(ctx context.Context, in *pb.ConditionListRequest) (*pb.ConditionListResponse, error) {
	l := logic.NewGetConditionListLogic(ctx, s.svcCtx)
	return l.GetConditionList(in)
}

func (s *CinemaRpcServer) GetCinema(ctx context.Context, in *pb.GetCinemaRequest) (*pb.GetCinemaResponse, error) {
	l := logic.NewGetCinemaLogic(ctx, s.svcCtx)
	return l.GetCinema(in)
}

func (s *CinemaRpcServer) GetShowList(ctx context.Context, in *pb.GetShowListRequest) (*pb.GetShowListResponse, error) {
	l := logic.NewGetShowListLogic(ctx, s.svcCtx)
	return l.GetShowList(in)
}

func (s *CinemaRpcServer) GetHallSeats(ctx context.Context, in *pb.GetHallSeatsRequest) (*pb.GetHallSeatsResponse, error) {
	l := logic.NewGetHallSeatsLogic(ctx, s.svcCtx)
	return l.GetHallSeats(in)
}

func (s *CinemaRpcServer) DeductSeats(ctx context.Context, in *pb.DeductSeatsRequest) (*pb.DeductSeatsResponse, error) {
	l := logic.NewDeductSeatsLogic(ctx, s.svcCtx)
	return l.DeductSeats(in)
}

func (s *CinemaRpcServer) DeductSeatsRollBack(ctx context.Context, in *pb.DeductSeatsRequest) (*pb.DeductSeatsResponse, error) {
	l := logic.NewDeductSeatsRollBackLogic(ctx, s.svcCtx)
	return l.DeductSeatsRollBack(in)
}
