// Code generated by goctl. DO NOT EDIT!
// Source: cinema.proto

package cinemarpc

import (
	"context"

	"MaoerMovie/service/cinema-rpc/types/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BrandCondition        = pb.BrandCondition
	CinemaListRequest     = pb.CinemaListRequest
	CinemaListResponse    = pb.CinemaListResponse
	CinemaPreview         = pb.CinemaPreview
	CinemaShow            = pb.CinemaShow
	ConditionListRequest  = pb.ConditionListRequest
	ConditionListResponse = pb.ConditionListResponse
	DistrictCondition     = pb.DistrictCondition
	GetCinemaRequest      = pb.GetCinemaRequest
	GetCinemaResponse     = pb.GetCinemaResponse
	GetHallSeatsRequest   = pb.GetHallSeatsRequest
	GetHallSeatsResponse  = pb.GetHallSeatsResponse
	GetShowListRequest    = pb.GetShowListRequest
	GetShowListResponse   = pb.GetShowListResponse
	HallType              = pb.HallType

	CinemaRpc interface {
		GetCinemaList(ctx context.Context, in *CinemaListRequest, opts ...grpc.CallOption) (*CinemaListResponse, error)
		GetConditionList(ctx context.Context, in *ConditionListRequest, opts ...grpc.CallOption) (*ConditionListResponse, error)
		GetCinema(ctx context.Context, in *GetCinemaRequest, opts ...grpc.CallOption) (*GetCinemaResponse, error)
		GetShowList(ctx context.Context, in *GetShowListRequest, opts ...grpc.CallOption) (*GetShowListResponse, error)
		GetHallSeats(ctx context.Context, in *GetHallSeatsRequest, opts ...grpc.CallOption) (*GetHallSeatsResponse, error)
	}

	defaultCinemaRpc struct {
		cli zrpc.Client
	}
)

func NewCinemaRpc(cli zrpc.Client) CinemaRpc {
	return &defaultCinemaRpc{
		cli: cli,
	}
}

func (m *defaultCinemaRpc) GetCinemaList(ctx context.Context, in *CinemaListRequest, opts ...grpc.CallOption) (*CinemaListResponse, error) {
	client := pb.NewCinemaRpcClient(m.cli.Conn())
	return client.GetCinemaList(ctx, in, opts...)
}

func (m *defaultCinemaRpc) GetConditionList(ctx context.Context, in *ConditionListRequest, opts ...grpc.CallOption) (*ConditionListResponse, error) {
	client := pb.NewCinemaRpcClient(m.cli.Conn())
	return client.GetConditionList(ctx, in, opts...)
}

func (m *defaultCinemaRpc) GetCinema(ctx context.Context, in *GetCinemaRequest, opts ...grpc.CallOption) (*GetCinemaResponse, error) {
	client := pb.NewCinemaRpcClient(m.cli.Conn())
	return client.GetCinema(ctx, in, opts...)
}

func (m *defaultCinemaRpc) GetShowList(ctx context.Context, in *GetShowListRequest, opts ...grpc.CallOption) (*GetShowListResponse, error) {
	client := pb.NewCinemaRpcClient(m.cli.Conn())
	return client.GetShowList(ctx, in, opts...)
}

func (m *defaultCinemaRpc) GetHallSeats(ctx context.Context, in *GetHallSeatsRequest, opts ...grpc.CallOption) (*GetHallSeatsResponse, error) {
	client := pb.NewCinemaRpcClient(m.cli.Conn())
	return client.GetHallSeats(ctx, in, opts...)
}
