// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package server

import (
	"context"

	"MaoerMovie/service/order-rpc/internal/logic"
	"MaoerMovie/service/order-rpc/internal/svc"
	"MaoerMovie/service/order-rpc/types/pb"
)

type OrderRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderRpcServer
}

func NewOrderRpcServer(svcCtx *svc.ServiceContext) *OrderRpcServer {
	return &OrderRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderRpcServer) CreateOrder(ctx context.Context, in *pb.CreateOrderRequest) (*pb.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderRpcServer) GetOrderDetail(ctx context.Context, in *pb.GetOrderDetailRequest) (*pb.GetOrderDetailResponse, error) {
	l := logic.NewGetOrderDetailLogic(ctx, s.svcCtx)
	return l.GetOrderDetail(in)
}

func (s *OrderRpcServer) GetOrderList(ctx context.Context, in *pb.GetOrderListRequest) (*pb.GetOrderListResponse, error) {
	l := logic.NewGetOrderListLogic(ctx, s.svcCtx)
	return l.GetOrderList(in)
}

func (s *OrderRpcServer) GetPaidOrderList(ctx context.Context, in *pb.GetOrderListRequest) (*pb.GetPaidOrderListResponse, error) {
	l := logic.NewGetPaidOrderListLogic(ctx, s.svcCtx)
	return l.GetPaidOrderList(in)
}

func (s *OrderRpcServer) GetSoldSeats(ctx context.Context, in *pb.GetSoldSeatsRequest) (*pb.GetSoldSeatsResponse, error) {
	l := logic.NewGetSoldSeatsLogic(ctx, s.svcCtx)
	return l.GetSoldSeats(in)
}

func (s *OrderRpcServer) SetOrderPaid(ctx context.Context, in *pb.SetOrderPaidRequest) (*pb.SetOrderPaidResponse, error) {
	l := logic.NewSetOrderPaidLogic(ctx, s.svcCtx)
	return l.SetOrderPaid(in)
}

func (s *OrderRpcServer) SetOrderPaidRollback(ctx context.Context, in *pb.SetOrderPaidRequest) (*pb.SetOrderPaidResponse, error) {
	l := logic.NewSetOrderPaidRollbackLogic(ctx, s.svcCtx)
	return l.SetOrderPaidRollback(in)
}

func (s *OrderRpcServer) CreateOrderRollback(ctx context.Context, in *pb.CreateOrderRequest) (*pb.CreateOrderRequest, error) {
	l := logic.NewCreateOrderRollbackLogic(ctx, s.svcCtx)
	return l.CreateOrderRollback(in)
}
