// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cinemaFieldNames          = builder.RawFieldNames(&Cinema{})
	cinemaRows                = strings.Join(cinemaFieldNames, ",")
	cinemaRowsExpectAutoSet   = strings.Join(stringx.Remove(cinemaFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	cinemaRowsWithPlaceHolder = strings.Join(stringx.Remove(cinemaFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"

	cacheCinemaIdPrefix = "cache:cinema:id:"
)

type (
	cinemaModel interface {
		Insert(ctx context.Context, data *Cinema) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Cinema, error)
		Update(ctx context.Context, data *Cinema) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCinemaModel struct {
		sqlc.CachedConn
		table string
	}

	Cinema struct {
		Id          int64  `db:"id"`           // 主键编号
		CinemaName  string `db:"cinema_name"`  // 影院名称
		CinemaPhone string `db:"cinema_phone"` // 影院电话
		BrandId     int64  `db:"brand_id"`     // 品牌编号
		DistrictId  int64  `db:"district_id"`  // 区域编号
		HallIds     string `db:"hall_ids"`     // 包含的影厅类型,以/作为分割
		CinemaImgs  string `db:"cinema_imgs"`  // 影院图片地址
		Address     string `db:"address"`      // 影院地址
		MinPrice    int64  `db:"min_price"`    // 最低票价
	}
)

func newCinemaModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultCinemaModel {
	return &defaultCinemaModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`cinema`",
	}
}

func (m *defaultCinemaModel) Delete(ctx context.Context, id int64) error {
	cinemaIdKey := fmt.Sprintf("%s%v", cacheCinemaIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, cinemaIdKey)
	return err
}

func (m *defaultCinemaModel) FindOne(ctx context.Context, id int64) (*Cinema, error) {
	cinemaIdKey := fmt.Sprintf("%s%v", cacheCinemaIdPrefix, id)
	var resp Cinema
	err := m.QueryRowCtx(ctx, &resp, cinemaIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cinemaRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCinemaModel) Insert(ctx context.Context, data *Cinema) (sql.Result, error) {
	cinemaIdKey := fmt.Sprintf("%s%v", cacheCinemaIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, cinemaRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CinemaName, data.CinemaPhone, data.BrandId, data.DistrictId, data.HallIds, data.CinemaImgs, data.Address, data.MinPrice)
	}, cinemaIdKey)
	return ret, err
}

func (m *defaultCinemaModel) Update(ctx context.Context, data *Cinema) error {
	cinemaIdKey := fmt.Sprintf("%s%v", cacheCinemaIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cinemaRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CinemaName, data.CinemaPhone, data.BrandId, data.DistrictId, data.HallIds, data.CinemaImgs, data.Address, data.MinPrice, data.Id)
	}, cinemaIdKey)
	return err
}

func (m *defaultCinemaModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheCinemaIdPrefix, primary)
}

func (m *defaultCinemaModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cinemaRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCinemaModel) tableName() string {
	return m.table
}
