// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	districtFieldNames          = builder.RawFieldNames(&District{})
	districtRows                = strings.Join(districtFieldNames, ",")
	districtRowsExpectAutoSet   = strings.Join(stringx.Remove(districtFieldNames, "`id`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`"), ",")
	districtRowsWithPlaceHolder = strings.Join(stringx.Remove(districtFieldNames, "`id`", "`update_time`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`"), "=?,") + "=?"

	cacheDistrictIdPrefix = "cache:district:id:"
)

type (
	districtModel interface {
		Insert(ctx context.Context, data *District) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*District, error)
		Update(ctx context.Context, data *District) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDistrictModel struct {
		sqlc.CachedConn
		table string
	}

	District struct {
		Id           int64  `db:"id"`            // 主键编号
		CityName     string `db:"city_name"`     // 市名
		DistrictName string `db:"district_name"` // 区名
	}
)

func newDistrictModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultDistrictModel {
	return &defaultDistrictModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`district`",
	}
}

func (m *defaultDistrictModel) Delete(ctx context.Context, id int64) error {
	districtIdKey := fmt.Sprintf("%s%v", cacheDistrictIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, districtIdKey)
	return err
}

func (m *defaultDistrictModel) FindOne(ctx context.Context, id int64) (*District, error) {
	districtIdKey := fmt.Sprintf("%s%v", cacheDistrictIdPrefix, id)
	var resp District
	err := m.QueryRowCtx(ctx, &resp, districtIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", districtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDistrictModel) Insert(ctx context.Context, data *District) (sql.Result, error) {
	districtIdKey := fmt.Sprintf("%s%v", cacheDistrictIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, districtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CityName, data.DistrictName)
	}, districtIdKey)
	return ret, err
}

func (m *defaultDistrictModel) Update(ctx context.Context, data *District) error {
	districtIdKey := fmt.Sprintf("%s%v", cacheDistrictIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, districtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CityName, data.DistrictName, data.Id)
	}, districtIdKey)
	return err
}

func (m *defaultDistrictModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDistrictIdPrefix, primary)
}

func (m *defaultDistrictModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", districtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDistrictModel) tableName() string {
	return m.table
}
