// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"MaoerMovie/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/email/code/send",
				Handler: EmailCodeSendHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/userinfo",
				Handler: UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh/auth",
				Handler: RefreshAuthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update/info",
				Handler: UpdateInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update/pass",
				Handler: UpdatePassHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
