// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterRequest struct {
	Name      string `json:"name"`
	Gender    int64  `json:"gender"`
	Mobile    string `json:"mobile"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	EmailCode string `json:"emailCode,optional"`
	PhoneCode string `json:"phoneCode,optional"`
}

type RegisterResponse struct {
	Id int64 `json:"id"`
}

type UserInfoResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Email  string `json:"email"`
	Mobile string `json:"mobile"`
	Status int64  `json:"status"`
}

type EmailCodeSendRequest struct {
	Email string `json:"email"`
}

type EmailCodeSendResponse struct {
}

type RefreshAuthResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UpdateInfoRequest struct {
	Name   string `json:"name,optional"`
	Gender int64  `json:"gender,optional"`
	Mobile string `json:"mobile,optional"`
	Email  string `json:"email,optional"`
}

type UpdateInfoResponse struct {
}

type UpdatePassRequest struct {
	Password    string `json:"password"`
	NewPassword string `json:"new_password"`
}

type UpdatePassResponse struct {
}
